/**
 * Build the Draft board dataset. Server-side only — the Draft API sends no
 * CORS headers, exactly like the main game's.
 *
 * No league id is involved. The draft assistant is deliberately usable without
 * one, so this script only ever fetches public, league-independent data.
 *
 * On any upstream failure the previous files are left untouched: the browser
 * depends on the committed dataset, never on live API access.
 */
import { getJSON } from './lib/http.mjs';
import { readJSON, writeJSONIfChanged } from './lib/io.mjs';

const DRAFT_API = 'https://draft.premierleague.com/api';
const CLASSIC_API = 'https://fantasy.premierleague.com/api';
const DIR = 'data/draft';

const num = (v) => {
  const n = typeof v === 'number' ? v : parseFloat(v);
  return Number.isFinite(n) ? n : 0;
};

const prior = await readJSON(`${DIR}/prior-2526.json`);
if (!prior?.players) {
  throw new Error('missing data/draft/prior-2526.json — run `npm run freeze-prior` first');
}

console.log('→ draft bootstrap-static');
const draftBoot = await getJSON(`${DRAFT_API}/bootstrap-static`, { browserUA: true })
  .catch((e) => { console.warn(`  draft bootstrap failed: ${e.message}`); return null; });

console.log('→ classic bootstrap-static');
const classicBoot = await getJSON(`${CLASSIC_API}/bootstrap-static/`, { browserUA: true })
  .catch((e) => { console.warn(`  classic bootstrap failed: ${e.message}`); return null; });

if (!classicBoot?.elements?.length) {
  console.warn('✗ no classic payload — leaving the committed dataset untouched');
  process.exit(0);
}

/* The Draft settings are the authoritative scoring rules. If the Draft API is
   down we keep whatever config is already committed rather than inventing one. */
if (draftBoot?.settings) {
  await writeJSONIfChanged(`${DIR}/config.json`, {
    scoring: draftBoot.settings.scoring,
    squad: draftBoot.settings.squad,
    league: draftBoot.settings.league,
  });
  console.log('  wrote scoring + squad config');
} else {
  console.warn('  no draft settings — keeping the committed config');
}

// draft_rank and the Draft element id are enrichments. Join on code: 21 of 587
// players have different ids in the two games, so joining on id is wrong.
const draftByCode = new Map((draftBoot?.elements || []).map((p) => [p.code, p]));

const players = classicBoot.elements.map((p) => {
  const d = draftByCode.get(p.code);
  return {
    code: p.code,
    id: d?.id ?? p.id,
    element_type: p.element_type,
    team: p.team,
    web_name: p.web_name,
    first_name: p.first_name,
    second_name: p.second_name,
    status: p.status,
    chance_of_playing_next_round: p.chance_of_playing_next_round,
    news: p.news || '',
    now_cost: num(p.now_cost), // informational only — never used in ranking
    draft_rank: d ? num(d.draft_rank) : (prior.players[p.code]?.draft_rank ?? null),
    penalties_order: p.penalties_order ?? null,
    prior: prior.players[p.code] ?? null,
  };
}).filter((p) => p.prior);

// Real club strength ratings, for js/model.js's teamDefence() fallback when a
// club has too little prior-season data (newly promoted sides). Sourced from
// the live classic payload, never from data/bootstrap.json — that file is
// synthetic seed data regenerated by scripts/make-sample.mjs on every test run.
const teams = (classicBoot.teams || []).map((t) => ({
  id: t.id,
  name: t.name,
  short_name: t.short_name,
  strength_overall_home: num(t.strength_overall_home),
  strength_overall_away: num(t.strength_overall_away),
}));

await writeJSONIfChanged(`${DIR}/players.json`, {
  builtAt: new Date().toISOString(),
  priorSeason: prior.season,
  players,
  teams,
});
console.log(`✓ ${players.length} players on the board, ${teams.length} teams`);

/* ------------------------------------------------------------------ *
 * Optional: mirror the Draft league
 *
 * Everything above works with no league id, and that stays true — the draft
 * assistant must never require one. This block runs only when
 * FPL_DRAFT_LEAGUE_ID is set, and any failure leaves the committed file alone.
 *
 * What it buys: real manager names instead of "Slot 4", and live ownership so
 * opponent rosters maintain themselves through the season instead of being
 * typed in.
 * ------------------------------------------------------------------ */
const LEAGUE_ID = (process.env.FPL_DRAFT_LEAGUE_ID || '').trim();
// Which of the league's entries is the owner's. The Draft API cannot tell us
// without a login, so it is configured; without it the hub can still show every
// squad, it just cannot mark one of them "you".
const MY_ENTRY_ID = Number(process.env.FPL_DRAFT_ENTRY_ID || 0) || null;

if (!LEAGUE_ID) {
  console.log('  no FPL_DRAFT_LEAGUE_ID — skipping league mirror (this is fine)');
} else {
  console.log(`→ draft league ${LEAGUE_ID}`);

  // Draft element ids are NOT classic element ids — 21 of 587 differ. The board
  // is keyed on classic ids, so ownership must be translated through `code`
  // before it is written, or a handful of players silently become the wrong
  // player. This is the single most dangerous join in the project.
  const classicIdByCode = new Map(classicBoot.elements.map((p) => [p.code, p.id]));
  const classicIdByDraftId = new Map();
  for (const d of draftBoot?.elements || []) {
    const classicId = classicIdByCode.get(d.code);
    if (classicId != null) classicIdByDraftId.set(d.id, classicId);
  }

  const details = await getJSON(`${DRAFT_API}/league/${LEAGUE_ID}/details`, { browserUA: true })
    .catch((e) => { console.warn(`  league details failed: ${e.message}`); return null; });

  const status = await getJSON(`${DRAFT_API}/league/${LEAGUE_ID}/element-status`, { browserUA: true })
    .catch((e) => { console.warn(`  element-status failed: ${e.message}`); return null; });

  // Round-1 pick order IS the draft slot, so the choices endpoint is what turns
  // an entry id into a slot number. It is empty until the draft starts.
  const choices = await getJSON(`${DRAFT_API}/draft/${LEAGUE_ID}/choices`, { browserUA: true })
    .catch(() => null);

  if (!details?.league) {
    console.warn('  ✗ no league payload — leaving any committed league.json untouched');
  } else {
    const slotByEntry = new Map();
    for (const c of choices?.choices || []) {
      if (c.round === 1 && c.entry != null) slotByEntry.set(c.entry, c.pick);
    }

    const managers = (details.league_entries || []).map((e) => ({
      entryId: e.entry_id ?? e.id ?? null,
      leagueEntryId: e.id ?? null,
      teamName: e.entry_name ?? null,
      manager: [e.player_first_name, e.player_last_name].filter(Boolean).join(' ') || null,
      shortName: e.short_name ?? null,
      slot: slotByEntry.get(e.entry_id ?? e.id) ?? null,
    }));

    // element → owning league entry, translated to classic ids.
    const ownership = {};
    let untranslated = 0;
    for (const row of status?.element_status || []) {
      if (row.owner == null) continue;
      const classicId = classicIdByDraftId.get(row.element);
      if (classicId == null) { untranslated += 1; continue; }
      ownership[classicId] = row.owner;
    }
    if (untranslated) console.warn(`  ${untranslated} owned elements could not be mapped to a classic id`);

    /* ---------------------------------------------------------------- *
     * derive the transaction log
     * ---------------------------------------------------------------- *
     * league/{id}/transactions and draft/{id}/trades both 404 without a
     * login, so the moves themselves are not published. Ownership is, and a
     * change of owner IS a transaction — so the log is built by diffing this
     * refresh against the last committed one and appending what moved.
     *
     * It therefore starts empty and accumulates from the first refresh after
     * this ships. It cannot recover history it never saw, and it should not
     * pretend otherwise.
     */
    const previous = await readJSON(`${DIR}/league.json`).catch(() => null);
    const log = (await readJSON(`${DIR}/transactions.json`).catch(() => null)) || { events: [] };
    if (previous?.ownership && Object.keys(previous.ownership).length) {
      const now = new Date().toISOString();
      const seen = new Set([...Object.keys(previous.ownership), ...Object.keys(ownership)]);
      const fresh = [];
      for (const id of seen) {
        const before = previous.ownership[id] ?? null;
        const after = ownership[id] ?? null;
        if (before === after) continue;
        fresh.push({
          at: now,
          element: Number(id),
          from: before,
          to: after,
          kind: before == null ? 'added' : after == null ? 'dropped' : 'traded',
        });
      }
      if (fresh.length) {
        log.events.push(...fresh);
        // A season of waivers is small, but unbounded growth is still a bug.
        if (log.events.length > 2000) log.events = log.events.slice(-2000);
        console.log(`  ${fresh.length} ownership change${fresh.length === 1 ? '' : 's'} recorded`);
      }
    }
    // Written every run, changes or not, so the page always has a file to read
    // rather than having to treat "missing" and "nothing happened yet" alike.
    log.updatedAt = new Date().toISOString();
    await writeJSONIfChanged(`${DIR}/transactions.json`, log);

    const changed = await writeJSONIfChanged(`${DIR}/league.json`, {
      fetchedAt: new Date().toISOString(),
      leagueId: Number(LEAGUE_ID),
      myEntryId: MY_ENTRY_ID,
      name: details.league.name ?? null,
      size: details.league.max_entries ?? managers.length,
      draftAt: details.league.draft_dt ?? null,
      draftStatus: details.league.draft_status ?? null,
      pickTimeLimit: details.league.draft_pick_time_limit ?? null,
      tradesEnabled: details.league.trades === 'y',
      managers,
      ownership,
      // Provenance, per the Phase 2 brief: every consumer should be able to see
      // where a field came from and how stale it is.
      source: { managers: 'draft-api', ownership: 'draft-api', slots: choices?.choices?.length ? 'draft-api' : 'unknown' },
    });
    console.log(`  ${managers.length} managers, ${Object.keys(ownership).length} owned players${changed ? '' : ' (unchanged)'}`);
  }
}
